   - name: Add epel repository
     yum_repository:
       name: epel
       description: EPEL YUM repo
       baseurl: http://download.fedoraproject.org/pub/epel/$releasever/$basearch/
       gpgcheck: no
     when: ansible_os_family == "RedHat"
